deployment:
  tasks:
    - echo "Starting frontend deployment..."
    - cd $HOME/frontend
    - git pull origin main
    - npm install
    - npm run build
    - cp -r $HOME/frontend/editedge-crm/dist/* $HOME/crm.editedgemultimedia.com/

